# 服务设置
server:
  server_port: :8000
  jwtKey: 8ue3928nusah867
# 数据库设置
database:
  db_host: wejectchan.mysql.cn-chengdu.rds.aliyuncs.com
  db_port: 3306
  db_user: wejectchan
  db_password: QzgwEhBFx3ibuz
  db_name: lookarm

